### ISSUE TITLE
Disambiguate caret position at wrapped line boundaries

### ISSUE THREAD

**Issue by banga** [w3c/editing#189] opened 2019-01-30 01:00 UTC
Hello,

There's a gap in the current `Range` and `Selection` APIs for wrapped lines, where the position at the end of the first line and the beginning of the second line cannot be differentiated.
For example, if you have the following content:
```
AAA
BBB
```
Then if you position the caret at the end of `AAA` and get the `Range`, it is identical to when you position the caret before `BBB`. Similarly, if you try to move the caret to the end of `AAA` by creating a new `Range`, most browsers position the caret to be on the next line.

I've also tried using `getBoundingClientRect` and `getClientRects` to disambiguate the two, which doesn't work. Even if it did, there would still be a need to be able to position things at the end of the line programmatically.

The primary use-case for this is to be able to improve upon the default behavior of `up/down/home/end` keys for moving the caret in complex documents. For e.g. if you have a `cE="false"` node at the end of a wrapped line, pressing `end` takes the caret to the beginning of the next line, which is not what is expected. You can see this in action in "Case 3: Line wrapping" in https://y2wm48yqm9.codesandbox.io/

**Comment by johanneswilm** [comment] 2019-03-22 17:52
Hey, this has actually been discussed before [1]. There are two issues in the selection API tracking this [2] [3]. So I am closing this issue as a duplicate of those two.

[1] https://www.w3.org/2015/08/23-webapps-minutes.html (search for "we want information in selection that says where the caret is")
[2] https://github.com/w3c/selection-api/issues/32 
[3] https://github.com/w3c/selection-api/issues/51

**Closed as completed by johanneswilm** 2019-03-22 17:52 UTC

**Comment by banga** [comment] 2019-03-22 17:57
Ah I see, thanks for the context!
