### ISSUE TITLE
What browser internals can be exposed to help us move the caret in (and against) the block direction?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#56] opened 2015-05-27 23:03 UTC
Moving the caret within the line is not that difficult to do in JavaScript. Moving it in the block direction (or 180 degrees in the opposite direction) is much more difficult. It would help a lot if the browser could expose something about where the caret would be if it were to go one line into either direction. But what could the browser expose that would give us that?

**Comment by rniwa** [comment] 2015-05-28 02:05
What are use cases for moving caret in block direction from JavaScript?

**Comment by johanneswilm** [comment] 2015-05-28 02:20
Because basically we cannot really trust the browser in move the caret where the app needs it to  anyway, so following @kojiishi's request:

> Are we not defining any default handlers for these intents? No default handles for arrow keys too?
> 
> The original intention of this issue is that I just want the behavior clearly defined, so if the spec defines no default handlers, things should be easier.

I have just turned the caret movement into intentions that aren't handled by the browser.

**Comment by rniwa** [comment] 2015-05-28 02:28
I don't think we should be discussing how to design a new API without having a list of concre use cases and problems we're solving. Without that, we wouldn't know the criteria by which each proposal is evaluated.

When you say "[the app] cannot really trust the browser in move the caret where the app needs it", what kind of an app are we talking about?  e.g. presentation app, spreadsheet app, etc... And exactly in which scenario does the browser not handle caret movement correctly?  e.g. when a caret moves across an image in a word processing app.

**Comment by johanneswilm** [comment] 2015-05-28 02:32
@rniwa A simple writing editor app. Try to look at the source code of some of the many of the editor apps, They need to check and make sure the caret is actually where they want it before they do operation X or Y. Often one even needs to add small timeouts of 0 or 1 or alike to make it kind of work. If one just lets the browser do it, it just disappears or is normalized to go weird places, etc. .

**Comment by rniwa** [comment] 2015-05-28 02:36
@johanneswilm That's not a use case. That's a workaround some editors to address a concrete use case. What we need to understand is that for what problems those editors had to add a timer, etc...

**Comment by johanneswilm** [comment] 2015-05-28 02:51
Ok, I understand  that you want to understand why this is a problem. Let's for a moment forget about all the bugginess of contenteditable, and just think of a plain example in a browser that just works:

```

<div contenteditable=true>
<span class="digitalone"><span class="digitaltwo">Some words</span></span>
</div>

```

When writing at the end of  `digitalone` I want it to expand with the new text. When writing in `digitaltwo` I want new text at the end to fall outside of it. In practice, the only way to achieve this is by controlling the caret behaviro directly by JavaScript and doing various tricks. At anyr ate, I'm sure you'll easily find thousands of other such examples. Just look a little bit at the code of editors and you should easily find it. This is another of the top reasons why contenteditable needs to be replaced.

**Comment by rniwa** [comment] 2015-05-28 03:03
Okay, but scripts can just adjust ranges in JavaScript without moving the caret in block direction in this case, right?  i.e. the app could let the browser move the caret and then adjust the caret as needed once the caret has been moved by the browser.

What I'd like to understand is the use case that involves the web apps moving the caret in block direction since that's what's being asked here.

**Comment by johanneswilm** [comment] 2015-05-28 03:14
Yes, so imagine the above example, but with way more text:

```
<adiv contenteditable=true>
blablab labla... 
<span class="digitalone"><span class="digitaltwo">Some words</span></span> 
blabbal abla...
</div>
```

The caret is somewhere in the second "blablabala" portion and the user clicks "up" and the caret just happens to go at the end of "Some words". Now where is it really? Inside of both spans, just one or outside of both? Difficult to say.

Having the "the browser moves the caret and then the user adjusts it" is what is going on today with some success. If you want the caret to insert something within the second span, one may insert a letter behind the first span, then select the letter, then paste whatever one really wanted to insert. That should pretty much do it. But it's not very clean and not in line with the idea of using intentions. Also because you need to check the caret position **every** time you move the caret in any direction. So instead of moving automatically, it would be nicer if the browser simply said where it would move it, and one can then adjust that before the actual movement takes place.

**Comment by rniwa** [comment] 2015-05-28 03:18
Doesn't that mean we just need something like "beforeselectionchange" event that exposes where the selection will be and let the website override the new selection as needed?

**Comment by johanneswilm** [comment] 2015-05-28 03:38
I think that should cover it, yes. That would probably be an even cleaner approach.

**Comment by rniwa** [comment] 2015-05-28 03:42
Okay, we should probably do that instead then.  It's probably not that hard to add such an event as long as we only fire the event for user-initiated selection changes (so that we don't end up in mutually recursive UA/author code calls as in mutation events that triggers all sorts of hells).

**Comment by johanneswilm** [comment] 2015-05-28 04:13
OK, that sounds like a solution. Should that be added to the selection API document?

I previously wrote something about basic caret movement before it was replaced with intentions. I can re-add that to this spec as basis for further discussion.

**Comment by rniwa** [comment] 2015-05-28 04:16
It doesn't seem like a selection API extension, yes.

**Comment by johanneswilm** [comment] 2015-05-28 04:24
It does or it doesn't?

**Comment by rniwa** [comment] 2015-05-28 06:35
Oops, I meant to say "it does".

**Comment by ctalau** [comment] 2015-05-28 06:47
@rniwa 

> Doesn't that mean we just need something like "beforeselectionchange" event that exposes where the selection will be and let the website override the new selection as needed?

Consider the following use case. 

```
verrrry looooong liiineeee
short line
verrrry looooong liiin|eeee
```

The caret is marked as a | (pipe) symbol. When the user presses the UP key twice, the caret temporarily moves to the end of the short line and then back to the same X axis coordinate on the top line:  

```
verrrry looooong liiin|eeee
short line
verrrry looooong liiineeee
```

So, when the user moves UP/DOWN, we need to override the UA selection but keep this magic X coordinate. However, when moving LEFT/RIGHT both the selection and magic X coordinate should be overridden.

Another examples of hidden selection state are:
- the pending click count. On some platforms double click means select a word, triple click means select the whole paragraph.
- whether the magnifying glass is shown on iOS or not

However, these two examples fall more into the mouse triggered selection changes.

**Comment by rniwa** [comment] 2015-05-28 07:03
I don't think we want to expose all those platform dependent selection states because that will make web apps dependent on a specific platform behavior.  We should instead come up with an abstraction like beforeselectionchange event and being able to save/restore selection states so that web apps can be written without having to know about all those platform-dependent behaviors.

**Comment by ctalau** [comment] 2015-05-28 11:47
I also think that these details should be left to the browser. I also agree with having a "beforeselectionchange" event. The problem is what a webapp should do in response to this event.

I assume that the web app will call the Selection API to set a different selection if the browser proposed one is not desirable. However the current API for setting a selection changes only the visible part of the selection-associated state, i.e. the selected range, and clears the hidden selection-associated state, so we need a better Selection API. 

Maybe we can have some selection-changing API that also receives the intent of the selection change.

**Comment by kojiishi** [comment] 2015-05-28 12:42
I'm not sure I follow this discussion properly, but for examples @johanneswilm and @ctalau raised, my understanding is browsers do some internal logic to do the work, which is not interoperable, but will raise events so that JS can change.

Is the request to expose currently hidden info so that JS can determine where to change? If my understanding is correct, I think what it should be is JS keeps such info by itself, because what info JS would need depends on how it wants to move. How caret moves when pressing up/down arrow key is I think part of the UX and one of the factors that determines how people likes the editor. One may want to keep X and flush it when left/right/mouse are used. Another may want to keep column and use different criteria to flush. One may want to use the behavior recommended for each OS, while someone else believes that consistent behavior across platform is the best.

So what API should define is to give enough opportunities (events) to JS to keep and flush such info, and access to X or column or whatever it wants to keep. The responsibility of when and what to keep is up to JS.

If we add an API to read "X of when up/down move started", and if an editor JS wants different behavior, the JS must wait until what s/he wants is defined in the spec, implemented, tested, and the spec goes CR/REC. We all would like to avoid that. Giving current info and events should give more flexibilities to editors.

So the question is, in order to build the behavior you editor JS developers want, are there enough events (left/right/up/down/home, ...) and properties (x, column, what else?)? Are they designed well enough so that such development is easy (e.g., if we have physical key events only, JS might need to list up all keys that moves caret to determine when to flush)?

**Comment by kojiishi** [comment] 2015-05-28 12:57
So an example of what @rniwa asked is something like, IIUC, as an editor JS developer, I want to build an editor that:
1. Remember logical-X when block-directional arrow key is pressed, if it was not remembered yet.
2. Left, right, ctrl+left, etc. all flushes what JS remembered above.
3. Want to set the selection by specifying the remembered logical-X if next key is up/down.

Make sure you can build your editor, add mouse, page up/down, home/end, etc. Now we know, for this example, browsers need to expose logical-X, beforeselectionchange event, a flag indicating whether it's inline or block-direction, and a method to set selection by logical-X.

Another JS editor developer may come up with different algorithm. We can then get a list of events, event properties, selection properties, and methods that suffices such needs.

Unless I misunderstand what @rniwa says...I hope not ;)

**Comment by johanneswilm** [comment] 2015-05-28 13:07
@kojiishi It depends a bit on whether or not to implement up/down (in European text) movement entirely in the JS. Initially, I thought that's the way we would go, but then @rniwa's comments made me think that maybe we shouldn't  do that anyway.

If we implement it entirely in JS, the thing that is somewhat complex is to find out what the carets current line-start offset is, what is in the next/last line at offset X, and if offset X is longer than the entire line, what the last possible position in that line is.

**Comment by ctalau** [comment] 2015-05-28 13:56
I second that implementing UP/DOWN caret navigation in JS is quite complex. I also agree with @kojiishi that specifying the UA hidden selection-associated state is not a good idea.

Maybe, we can use the `beforeselectionchange` event and add a `setResultRange` method to it that can be used to change the selection. This method would know the user intention, so it would be able to preserve whatever hidden selection-related state the UA uses.

```
document.addEventListener('beforeselectionchange', function(e){
    var sel = e.targetRange;
    var resultSel = ...;
    e.setResultRange(resultSel);
});
```

This would be similar to the Clipboard Events, where you can use the `clipboardData` event property to specify the actual data to be copied.

**Comment by rniwa** [comment] 2015-05-29 05:08
@kojiishi : I don't think we want to expose x-coordinate because preserving x-coordinate should really be considered as a platform/browser specific behavior.  It should encapsulated in whatever abstraction we come up.

@ctalau : I don't think range would quite work because there a single DOM position may represent two visual positions for the caret (e.g. before and after a line wrap).

**Comment by ctalau** [comment] 2015-05-29 05:47
@rniwa : I agree that there is some ambiguity if we use the range. This is a more general problem that should be addressed by the Selection API spec. This occurs every time when the script sets the selection.

But in the case of `beforeselectionchange` the UA already knows the user intention so it can use this information to disambiguate. For example, if the intent is `caretLineEnd` it would choose the position before line wrap.

If the script requires a finer control it can call directly the (improved) Selection API.

**Comment by johanneswilm** [comment] 2015-05-29 16:30
@rniwa @kojiishi Could you agree on what to give us access to? I would prefer if the default behavior is platform/browser specific, but that beyond that the JS is free to do whatever it wants.

Right now what we already kind of have access is the bounding box of a collapsed range (something like document.getSelection().getRangeAt(0).getClientRects()[0] ), to the degree that this can be relied upon. The JS then guestimates where the caret position in the line above would be, and tries out the bounding boxes of a few collapsed ranges and takes the closest match. So this can be done already, it's just rather cumbersome. Please keep that in mind when thinking of restricting JS editors: If you don't give them good access to what they really want, they will likely instead find a way around your restrictions, which likely will be somewhat slower due to the number of JS functions that have to be executed.

@rniwa If you don't want to expose that, what would you be willing to expose?

**Comment by teleclimber** [comment] 2015-05-29 18:46
I completely agree that one of the biggest "missing pieces" for editor devs is the complete lack of visibility into how a text node is laid out. To know where a line-wrap occurs we have to do some ridiculous hacky and error-prone gymnastics.

The browser should expose APIs that allow us to query a text node in various ways:

```
TextNode.getLineWraps() //array of character positions where line wraps

TextNode.getFromPosition( x, start );  // returns the character number closest to position x, starting at character number start.
```

These would have to be adapted for bidi text and vertical text, but you get the idea. With these we can iterate over our Elements and Text Nodes and find the desired range where we want to place the caret after a `move-caret-up` intent.

**Comment by johanneswilm** [comment] 2015-05-29 18:56
> I completely agree that one of the biggest "missing pieces" for editor devs is the complete lack of visibility into how a text node is laid out. To know where a line-wrap occurs we have to do some ridiculous hacky and error-prone gymnastics.

@teleclimber Are you aware of the  `Box Tree API` specification the `CSS Houdini` group is working on? http://dev.w3.org/houdini/box-tree-api/ . This will (hopefully) come, but it's somewhat further in the future, most likely.

I think that if for now we could simply get a function to "Where would caret go, if it should be close as possible to position X" or so, then we should be able to do most types of caret up/down movements ourselves.

**Comment by rniwa** [comment] 2015-05-29 22:07
I'm not certain introducing our own thing for editing will be useful since I have no reason to believe new editing API will be implemented before box tree API will be implemented in browsers.  e.g. we've been talking about new editing API as far as I've been working on WebKit (since 2009) and nothing has happened since then.

**Comment by johanneswilm** [comment] 2015-05-30 01:23
End the it's up to browser makers like yourself whether or not you want to ship it or fix contenteditable and when you will do it, but the spec should pretty much good to go very soon now. 
The box model is still in “dream stage”.

**Comment by johanneswilm** [comment] 2015-05-30 01:38
Also, if you have been thinking about this since 2009, everything should have been considered already and it's just a matter of putting it into writing. I myself have been pushing for fixing this since 2012, and I don't think this is a good point to give up. But it's kind of a now or never moment for a lot I think, and I hope Safari won't block this.

**Comment by johanneswilm** [comment] 2015-05-30 06:32
@rniwa: Given that we already can find the current caret position (using something like document.getSelection().getRangeAt(0).getClientRects()[0] ), I wonder if an `beforeselectionchange` event would give us all the information we need to have to implement the two versions of arrow up/down that have been mentioned. Especially given that it seems Safari is not willing to expose more simple underlying pieces of data for now. The `beforeselectionchange` event would give us a range corresponding to where the caret would be after the update, unless preventDefault is called on that event, right?

**Comment by ctalau** [comment] 2015-05-30 07:45
There are several use-cases for this new API:
1. Implement the caret in script.
   - Not the goal of this spec.
2. Reuse UA selection changing mechanisms. 
   - No API needed.
3. Reuse just the UA caret rendering: 
   - Need API to specify where exactly the caret is rendered at line wraps. `document.getSelection().getRangeAt(0).getClientRects()[0]` fails in this case.
   - Box Tree API would be great, but there are (tremendously hacky) workarounds even now.
4. Reuse UA selection changing mechanisms also, but avoid placing caret in some of the positions.
   - Cannot use the Selection API because it does not play nice with UA selection mechanisms, e.g. resets the magic X coordinate in UP/DOWN caret movement. 
   - An idea would be to have some way to specify which caret positions the user is allowed to place the caret at (CSS property, HTML attribute, etc.). This does not affect the specification of the Legal Caret Positions. WDYT?

**Comment by johanneswilm** [comment] 2015-05-30 12:30
> Need API to specify where exactly the caret is rendered at line wraps. document.getSelection().getRangeAt(0).getClientRects()[0] fails in this case.

In that case `getClientRects()` returns two places: one at the start of the line and one at the end, so we would want an inditation of which of the two corresponds to the actual visual drawing of the caret, right? To me it would be fine to add this information to the dictionary this function returns to the user, or alternatively to do it some other way. @rniwa and @kojiishi What would be the least intrusive for you?

For setting the caret as near as possible to  `point(X, Y)` what could we get?

> Reuse UA selection changing mechanisms also, but avoid placing caret in some of the positions.
> - Cannot use the Selection API because it does not play nice with UA selection mechanisms, e.g. resets the magic X coordinate in UP/DOWN caret movement. 

Things like this make me think that probably the default caret movement browsers include will be overwritten entirely by libraries anyway.

**Comment by ctalau** [comment] 2015-05-30 12:50
> In that case getClientRects() returns two places: one at the start of the line and one at the end, so we would want an inditation of which of the two corresponds to the actual visual drawing of the caret, right?

Exactly.

> For setting the caret as near as possible to point(X, Y) what could we get?

What about Document.caretPositionFromPoint()? [1]

> Things like this make me think that probably the default caret movement browsers include will be overwritten entirely by libraries anyway.

Maybe. Unless there is a way to configure the default behavior.

[1] http://www.w3.org/TR/cssom-view/#extensions-to-the-document-interface

**Comment by rniwa** [comment] 2015-05-31 04:49
The fact setting selection blows away x-coordinate is an orthogonal issue to be addressed.  Also, we need to think about various internal states of selection in the holistic view instead of talking about individual state.

**Comment by ctalau** [comment] 2015-05-31 12:08
> The fact setting selection blows away x-coordinate is an orthogonal issue to be addressed.

Probably. I was trying to say that the current Selection API + default behavior for the `beforeselectionchange` event does not help us to move the caret in block direction.

> Also, we need to think about various internal states of selection in the holistic view instead of talking about individual state.

Of course, I always used this just as an example.

**Comment by johanneswilm** [comment] 2015-05-31 12:12
Ok, but can we go ahead and add something like  `Document.caretPositionFromPoint()` and `Document.getCaretPosition()` to the spec, or do we have alternative proposals that will allow us to do the same thing?

We can then have a separate discussion on whether we should have default caret movement and what that should look like.

**Comment by ctalau** [comment] 2015-05-31 14:23
That's fine for me. At least we will have an use-case solved.

I think we can reuse the Document.caretPositionFromPoint() APi from CSSOM and add another one: Document.getCaretClientRect().

**Comment by kojiishi** [comment] 2015-06-02 02:13
> Ok, but can we go ahead and add something like `Document.caretPositionFromPoint()`

It's already in [CSS OM](http://www.w3.org/TR/cssom-view/#extensions-to-the-document-interface), what do you need to add?

Though, I think, unlike `elementFromPoint()` which looks similar, `caretPositionFromPoint()` needs to know how to resolve ambiguous caret position, so I think it should belong to the selection spec. If this looks reasonable, can someone talk to CSS WG to see what they think?

> and Document.getCaretPosition() to the spec, or do we have alternative proposals that will allow us to do the same thing?

Isn't it a one-liner:

```
window.getSelection().getRangeAt(0).getBoundingClientRect()
```

or are you talking about something different?

**Comment by ctalau** [comment] 2015-06-02 05:10
> or are you talking about something different?

The Range object cannot distinguish between a caret rendered visually at the end of a wrapped line or at the beginning of the next line. The two positions represent the same offset in a text node but visually they are different.

**Comment by rniwa** [comment] 2015-06-02 05:20
Yeah, before/after line break is one internal selection state that definitely needs to be exposed.

**Comment by johanneswilm** [comment] 2015-06-02 08:13
@kojiishi 

> It's already in CSS OM, what do you need to add?

The problem that a range cannot distinguish between the caret being before or after the line break is there for
- getting the caret X/Y position (`window.getSelection().getRangeAt(0).getBoundingClientRect()`), 
- setting the caret/selection to a specific range
- checking where a caret would go, 

right?

**Comment by kojiishi** [comment] 2015-06-02 08:46
Right, I forgot about that. And alsi bi-di.

So it looks to me that we have enough reasons to move the method to the Selection spec and update?

**Comment by johanneswilm** [comment] 2015-06-02 09:17
> So it looks to me that we have enough reasons to move the method to the Selection spec and update?

To me it would seem that would be a good place to move this to.

**Comment by rniwa** [comment] 2015-06-02 18:57
I'm afraid that exposing caret rect will make things worse for vertical writing mode (in Chinese, Japanese, Mongolian, etc...) as well as in bidirectional text where "split" caret appear at two points graphically to indicate two potential insertion points because most of web developers in the western world aren't even familiar with those text writing modes.

I'm more interested in what use case exposing caret rect is trying to solve, and address those use cases by other means instead.

**Comment by ctalau** [comment] 2015-06-02 19:03
Some use-cases: 
- show a tool-tip above the caret
- scroll the page if necessary such that the caret is visible 
- compute the next caret position the user expresses the intention to move one line up (the problem we started with)

**Comment by johanneswilm** [comment] 2015-06-02 19:59
@rniwa According to my Japanese contact, writing text in Japanese on the web currently still works mainly in the European ltr horizontal writing mode. Is that correct? Can you explain why it would make things worse to expose the information about where the caret actually is? If we don't have that information, we must continue to use the tricks we currently use and will for sure not think about other writing modes at all, because our source code already is so complex/unreadable just supporting ltr writing mode.

**Comment by johanneswilm** [comment] 2015-06-02 20:20
Other use-cases:
- Create a multi user editor and show the current position of the carets of the other editor participants (correctly)
- Save the last position of the caret when closing a document and restore it (correctly) when opening the document again.

**Comment by johanneswilm** [comment] 2015-06-02 22:45
Another possible use-case that hopefully noone will actually implement, but more than likely a lot of users may think is quite exciting:
- visual games with the caret. For example, a little gif-animation dog that walks across the screen and grabs the caret as if it were a bone and runs away with it as an "easter egg" type "screen saver".

**Comment by MartinDesigner** [comment] 2015-08-15 16:40
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by rniwa** [comment] 2015-08-15 16:49
> According to my Japanese contact, writing text in Japanese on the web currently still works mainly in the European ltr horizontal writing mode. Is that correct? Can you explain why it would make things worse to expose the information about where the caret actually is?

While it's true that most of text editors on the Web use horizontal writing mode, every popular word processing applications such as Microsoft Word on Desktop supports vertical writing mode since most of books and newspapers sold in Japan and Taiwan are still written vertically.  This is one area the Web is seriously lagging behind their native equivalents.  Since the whole point of this new API is to allow more apps and use cases, I don't think we should be aiming the low which is the current status quo.

As to why such an API makes worse for vertical writing mode, the problem is that the caret rect is shown as a horizontal bar in vertical writing mode, and depending on whether the block direction is from left to right (Mongolian) or right to left (Chinese/Japanese), such a tooltip must be shown on the left or the right of the caret respectively.

**Comment by rniwa** [comment] 2015-08-15 16:55
> - scroll the page if necessary such that the caret is visible 

We can probably add a capability to reveal selection based on the current selection.

> - compute the next caret position the user expresses the intention to move one line up (the problem we started with)

This can be addressed by `Selection.modify` working on a "detached" selection or some object that mimics selection behavior.  You can then `Selection.clone` and modify that "detached selection" as needed to figure out where it would go in DOM position.

> - Create a multi user editor and show the current position of the carets of the other editor participants (correctly)

This should be done using DOM positions since each such user may have a different screen resolution as well as fonts and therefore text layout would be different.  If you're doing a custom text layout, then you'd know exactly where the caret is so that's a moot point.

> - Save the last position of the caret when closing a document and restore it (correctly) when opening the document again.

Again, this should be done via DOM positions since the next time the user opens a browser, the document may layout differently.  Mozilla, for example, shows the caret at a different location at a boundary of bidi level based on heuristics so values such as that may need to be stored as well.  Regardless, I don't think knowing the CSS rect of the caret would help you restore caret since we don't have any API to set selection based on a CSS rect.

**Comment by rniwa** [comment] 2015-08-15 17:30
> - show a tool-tip above the caret

Also, I'm not even sure what this means for split caret (search for "Mac split cursor bidirectional text" to find more about it).  Are you gonna show the tooltip at two locations?  Or are you going to prefer one location or the other?

**Comment by Reinmar** [comment] 2015-08-16 17:17
I've read the whole thread today and I'd like to wrap it up a little bit as it was quite confusing due to lacking use cases and various topics that were mentioned.

## 1. Showing a box next to the caret.
- Examples:
  - Tooltip / floating toolbar – none that I know shows it next to a collapsed selection, but iOS, Medium or [AlloyEditor](http://alloyeditor.com/) do this for a non-collapsed selection. For usability reasons one may want to show the tooltip also for a collapsed selection, but perhaps none of the implementations do it right now because this is problematic.
  - Suggestion box for autocompletion feature – [At.js](http://ichord.github.io/At.js/).
- Problems:
  - Range (or a DOM position) does not include all necessary information about the caret position ([the end of line problem](https://github.com/w3c/editing/issues/56#issuecomment-107811366)),
  - [Split caret](https://github.com/w3c/editing/issues/56#issuecomment-131403158) (how the editor may understand which is "more important").
  - Vertical text (how the editor will understand that e.g. a suggestion box needs to be displayed on the right hand side instead of above the caret).
- Possible solutions:
  - [`Range.getClientRects()`](range.https://drafts.csswg.org/cssom-view/#dom-range-getclientrects) – does not solve the end of line problem as a range does not hold such information, hence while being useful, it's not a solution to this use case.
  - Other methods described in https://drafts.csswg.org/cssom-view – they are all oriented around range <-> point <-> position translations, so, again, despite being useful, none of the seem to be satisfactory.
  - `Selection.getCaretRects()` (such method would know about all the internals of the selection)
    - How would it work for a non-collapsed selection? IMO it should either return `null`/throw an error or be based on a selection direction (forward selection has a virtual caret on the right side – some editors even display it there). The latter seems most useful, but then what with directionless selections and multi-range selections?
    - What about the split carets? IMO, the editor is usually interested in the position of the next character insertion, so this rect could be marked (or be always available under index `0` of DOMRectList).
    - What about vertical text? @rniwa [mentioned](https://github.com/w3c/editing/issues/56#issuecomment-131400246) that depending on a language the "above" means actually "top", "left" or "right". Could exposing something like `Selection.caretOrientation` (top, left, right(, bottom)) solve the problem? Or perhaps such information can be represented as a range property/method?
  - `Selection.getCaretRect()` (like `selection.getCaretRects()` but returns information only for the "most important caret").
    - If we can spec "the most important caret" (based on next character insertion and direction), perhaps having `selection.getCaretRect()` instead of `selection.getCaretRects()` would be justifiable and simple.

## 2. Scrolling the page so the caret is visible.
- Examples:
  - Custom implementation of any algorithm which changes the selection such as pasting.
- Possible solutions:
  - As in use case 1.
  - `range.getClientRects()` could be enough unless this use case is affected by one of the problems from use case 1.
  - Additional argument for selection methods (`addRange()`, `extend()`) which will tell the browser whether to scroll. This would be useful, especially that IIRC some engines do scroll automatically, so ability to prevent that would be nice. I'm not sure though about bloating the API with such an argument.

## 3. Computing the next caret position the user expresses the intention to move one line up.

There weren't any super clear cases shown, so I haven't been sure myself whether the following workflow is sufficient or not:
1. Listen to `beforeselectionchange`. The browser should propose a new selection based on the user action.
2. If you don't like the proposed selection (e.g. it violates rules that you want to implement in your editor), then prevent the event and/or simply override that proposed selection using the existing APIs.

What I can see is that:
- Yes, `beforeselectionchange` which would expose what the browser is planning to do with the selection would be very useful.
- If you're building an editor without `cE=events` (so without the help of `beforeselectionchange`), then you should know yourself what to do with the selection.

However, I can think of a use cases when even with `cE=events` the `beforeselectionchange` event will not be enough. The case I've been dealing the most is caret movements (and selection in general) around non-editable blocks with editable elements inside (`^` is a selection):

```
<p>ABCDEF.</p>
<div cE=false>
    <p cE=events>
        GHIJKL.
    </p>
</div>
<p>MNO^PQR.</p>
```

Let's say that in such case browser tends to place caret inside GHIJKL when you press the UP key.

If the rules implemented by your editor say that this should select the `<div>`, then `beforeselectionchange` is enough for you – check the proposed selection and  if you didn't like it select the `<div>`.

If, however, you want the selection to jump over the `<div>` straight to ABCDEF, then you need additional API. Please also note that `Shift` may be pressed what extends this case to non-collapsed selections.

This makes a pretty clear use case for me, although IMO the whole case is not critical, as the `beforeselectionchange` enables other acceptable (from UX POV) solutions.

The additional API, as @rniwa suggested, could work on a clone of the real selection, what would solve the problem with internal X position:

```
editable.addEventListener( 'beforeselectionchange', function( evt ) {
    // If you want the Shift+Arrow behaviour.
    evt.selection.extend( DIRECTION_UP/DOWN/LEFT/RIGHT );

    // If you want the Arrow key behaviour.
    evt.selection.move( DIRECTION_UP/DOWN/LEFT/RIGHT );

    // Optionally, we could also emulate the Alt, Ctrl modifiers.
    evt.selection.move( DIRECTION_UP/DOWN/LEFT/RIGHT, JUMP_WORD/LINE );

    // If you want to probe to get out of the <div cE=false> (see the HTML example above).
    var clone = evt.selection.clone();

    while ( nonEditableDiv.contains( clone.anchorNode ) ) {
        clone.move( DIRECTION_UP );
    }
    evt.selection.move( clone ); // or clone.commit() for simplicity.
} );
```

(Edit: turns out I reinvented the wheel here, as this method already exists – https://github.com/w3c/selection-api/issues/37)

I think that an API that emulates the arrow keys behaviour could be easiest to implement and spec as this is what browsers already handle on key presses. Also, it does not expose any browser internal states (like the X position). For instance, in the "probing" scenario, the X position could be kept for the entire loop, so the final selection would be "ABC^DEF".

## 4. Create a multi user editor and show the current position of the carets of the other editor participants (correctly).

I agree with @rniwa – this should be done on DOM position and `range.getClientRects()`.

## 5. Save the last position of the caret when closing a document and restore it (correctly) when opening the document again.

The same as 4.

**Comment by johanneswilm** [comment] 2015-08-16 18:12
As for 4 and 5: Yes, right, the point was just to figure out whether the caret was before or after the line break and be able to place it there. But I saw that corresponding issues are being worked on in the Selection API now, so it's no longer a concern here.

**Comment by johanneswilm** [comment] 2015-08-16 21:48
@Reinmar: As for 3: Notice that we renamed the spec after removing any kind of caret movement or input behavior. This is still interesting of course and will have to be added eventually, but it is my understanding that this has been moved to a future "cE=caret" spec. In the meantime we need to be sure that the primitives are in place so that caret movement can be fully handled through JavaScript.

**Comment by Reinmar** [comment] 2015-08-17 07:47
> @Reinmar: As for 3: Notice that we renamed the spec after removing any kind of caret movement or input behavior. This is still interesting of course and will have to be added eventually, but it is my understanding that this has been moved to a future "cE=caret" spec.

Frankly speaking, I do not understand this move (stripping even caret movements), but I'll perhaps post a separate question about that. (Were there any discussions that would explain this decision?)

> In the meantime we need to be sure that the primitives are in place so that caret movement can be fully handled through JavaScript.

So perhaps the primitives are exactly as I described – selection methods simulating intentions of arrow keys? As they are supposed to replace the native default actions the most convenient for us, developers, would be if usage of them didn't require any additional tinkering. In 99% cases a developer using `cE=events` will try to recreate the native behaviour (that's also why I'm not sure if stripping this makes sense).

BTW. What about making a selection on touch screen devices and using mouse? So far the discussion was about caret movements and I can see that the input events explainer also describes only caret-related events. Have other cases been discussed already?

**Comment by johanneswilm** [comment] 2015-08-17 08:11
> Frankly speaking, I do not understand this move (stripping even caret movements), but I'll perhaps post a separate question about that. (Were there any discussions that would explain this decision?)

@Reinmar Well, there were two proposals (including them and not including them) and I went back and forth between including and removing those from the draft as opinions seemed to be in favor or against including it. We all noticed that standardizing caret movement would not be that easy as some browsers have very specific historic setups that they may not want to lose, and your boss @fredck came up with the idea to leave the typing module for now and instead just have this very basic intentions spec and later on add modules, including `caret`, `typing` and `return`. The discussions should all be on old tickets and the mailing list. Maybe this is something you guys want to discuss internally?

I personally don't care as much, as long as this issue doesn't end up meaning we won't get any further on the approval process at the F2F. If we don't approve anything, it may be another decade or two before someone else dares try.

> > In the meantime we need to be sure that the primitives are in place so that caret movement can be fully handled through JavaScript.
> 
> So perhaps the primitives are exactly as I described – selection methods simulating intentions of arrow keys? As they are supposed to replace the native default actions the most convenient for us, developers, would be if usage of them didn't require any additional tinkering. In 99% cases a developer using cE=events will try to recreate the native behaviour (that's also why I'm not sure if stripping this makes sense).

Well, as some people pointed out earlier here, the browsers behave differently (for example with BiDi in Firefox), and most likely JS editors will try to create a uniform behavior rather than behavior that differs from UA to UA.

Making UAs behave the exact same way would require a lot of speccing of how that would be that hasn't been done yet and which currently seems to have been postponed until a future `caret`-module, unless we change that inofficial plan.

I notice that Aloha Editor has implemented its own caret movement system. The Aloha editor doesn't use contentEditable, but selections. It cannot differentiate between end of line and beginning of line. That issue we have addressed through the proposals to the Selection API. 

I also see that ProseMirror hardly uses any of contentEditable, but keeps it in because it helps with the caret movement. 

So I wonder whether we should make a test where we just catch the arrow keys on contentEditable=true and preventDefault them and see how much is missing for implementing those entirely in Javascript, especially the arrow up/down keys would be of interest.

> BTW. What about making a selection on touch screen devices and using mouse? So far the discussion was about caret movements and I can see that the input events explainer also describes only caret-related events. Have other cases been discussed already?

Well, there was a ticket open for a long time asking for all the actions we may need. You can reopen it if you think there are things not mentioned. Some of these things are not only related to keyboard inputs but available through the right click menu. But check the ticket and discussion here:  https://github.com/w3c/editing/issues/52

**Comment by Reinmar** [comment] 2015-08-17 10:28
To avoid too big OT here, I posted #71.

But let me answer few things here:

>  your boss @fredck came up with the idea to leave the typing module for now and instead just have this very basic intentions spec and later on add modules, including caret, typing and return (... ) Maybe this is something you guys want to discuss internally?

We may have different opinions – nothing wrong with that ;). Besides, knowing @fredck's attitude I think that he might be misunderstood. Intentions is one thing, but no default actions is another.

> I notice that Aloha Editor has implemented its own caret movement system. The Aloha editor doesn't use contentEditable, but selections. 

Aloha 2 is still in early alpha AFAICS. It does not work on touch devices at all and the implementation is incomplete. I presume that the reasons for that are exactly as I described in #71.

Besides, these are not the only problems caused by stopping using `cE=true` (which is pretty similar to `cE=events`). I wrote an article recently where [I described a lot more potential issues](https://medium.com/medium-eng/why-contenteditable-is-terrible-122d8a40e480). Unless the spec we will produce will deal with all these problems, it will be unusable and hence `cE=true` will still be the only choice.

> I also see that ProseMirror hardly uses any of contentEditable, but keeps it in because it helps with the caret movement.

AFAICS, ProseMirror follows the same way as we defined for CKEditor 5 – don't let the browser change your content without your control, but do not interrupt (unless you want to change something) when it's doing its (harmless) job such as handling selection, composition, a11y, etc. This is much saner approach than dropping everything.

**Comment by johanneswilm** [comment] 2015-08-17 12:05
@Reinmar Do I guess correctly that then none of us quite know if it is possible to do block direction caret movement on all browsers/platforms using only JS without problems? I meantion those two projects, because:
- The ProseMirror developer is also behind CodeMirror, in which contenteditable is not used. The CodeMirror editor has also been adopted for richtext editing by some projects, yet for some reason he chose to use contenteditable on ProseMirror, and he mentions caret movement. He has responded earlier with some ideas about requirements, but we haven't heard as much from them as from you guys from CKEditor.
- The Aloha 2 people have at least tried to do block direction caret movement entirely in JS (without splitting lines manually), yet I don't think we have heard much from them since the Extensible Web Summit last fall in Berlin. So we don't know if they ran into fundamental issues with caret movement or whether they are dealing with many other bugs. From Github I can tell they have mainly been working on their Aloha 1 editor (the one that is built on contenteditable) for the last few months.

**Closed as completed** 2015-08-18 11:41 UTC
Labels: ContentEditableEvents
